apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
spec: # It define the behavior of the Deployment
  replicas: 2
  selector:
    matchLabels:
      app: web
  template: # It defines the Pod Definition
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flower-contianer
        image: sumanmd28/sre-test-image:1.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "200m" 
        ports:
        - containerPort: 3015

---

apiVersion: v1
kind: Service
metadata:
  name: flower-app-svc
spec:
  selector:
    app: web
  ports:
  - port: 3017
    targetPort: 3015
    protocol: TCP
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flower-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2
